# Generated by Django 5.0.3 on 2024-03-05 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_is_sale_product_sale_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
