# Generated by Django 5.0.3 on 2024-04-21 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='cap',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
