# Generated by Django 5.0.3 on 2024-04-23 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_address1',
            field=models.TextField(max_length=15000),
        ),
    ]
